### PR TITLE
Calculate per-host aggregate rows

### PR DESCRIPTION
**Pull request by dfberger**
Useful for understanding total usage of multi-homed or dual-stack hosts.

### CODE REVIEW

**Comment by fakuivan** [comment]
Could this somehow conflict with #7?

**Comment by dfberger** [comment]
@fakuivan - I haven't looked carefully at #7 but this change doesn't affect the underlying data gathering (including per-address up/down calculation) which are done by the wrtbwmon package.

**Comment by Kiougar** [comment]
I agree with @dfberger. This is supposed to group rows based on MAC address and #7 simply needed an extra case to check if IPs are the same. This should not affect #7.

**Comment by Kiougar** [comment]
BTW, thanks for this PR. This is a nice feature. 👍

**Pull request merged**
